version: '3.8'

services:
  frontend:
    build:
      context: ./careers-portal-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./careers-portal-frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    depends_on:
      - backend

  backend:
    build:
      context: ./careers-portal-backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./careers-portal-backend:/app
      - /app/node_modules
    environment:
      - MONGO_URI=mongodb://mongodb:27017/careerportal
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: 